#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  # watch:
  #   types: [started]
  workflow_dispatch:
    inputs:
      kernel:
        description: '选择需要编译的版本'
        required: true
        type: choice
        options:
          - 3.4
          - 4.4
      runs_on:
        description: '选择编译运行环境'
        required: true
        type: choice
        default: 'ubuntu-20.04'
        options:
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'
          - 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget \
        kmod python3-docutils libc-dev-bin
    - name: Clone source code
      env:
        KERNEL: ${{ inputs.kernel }}
      run: |
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/minax007/padavan-4.4.git /opt/rt-n56u
        else
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        fi
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: MI-R4A
        KERNEL: ${{ inputs.kernel }}
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        if [ $KERNEL = "4.4" ] ; then
        chmod +x modify_4.4.sh
        modify_4.4.sh
        else
        chmod +x modify.sh
        modify.sh
        fi
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
